### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by Enkelmann** [lucamassarelli/yarasafe#1]
I have found some typos:
- In the Ubuntu installation instructions `./configure.sh` should be `./configure` I think
- In *Ida-pro-plugin/Readme.md* `word2id.py` should be `word2id.json` and you should add the folder where to find it to the instructions
- In the example SAFE-rule in *Readme.md* I suppose `import safe` should be `import "safe"` ?

**Comment by lucamassarelli** [comment]
Yes! I correct all of these! Thank you for the suggestion!
